apiVersion: v1
kind: Pod
metadata:
  name: hub
  labels:
    name: hub
spec:
  containers:
  - name: minecraft
    image: paper-server
    imagePullPolicy: Never
    ports:
    - containerPort: 25565
    volumeMounts:
    - name: server-properties
      mountPath: /minecraft/server.properties
      subPath: server.properties
    - name: hub-spigot
      mountPath: /minecraft/spigot.yml
      subPath: spigot.yml
  volumes:
  - name: server-properties
    configMap:
      name: hub-server-properties
  - name: hub-spigot
    configMap:
      name: hub-spigot
