apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-pv
spec:
  capacity:
    storage: 10Gi # 必要に応じてサイズを変更
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard # ストレージクラスは環境に応じて変更
  hostPath:
    path: /path/to/minecraft # 実際のデータを保存するホストのパス
