apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
    spec:
      containers:
      - name: minecraft
        image: paper-server:latest
        imagePullPolicy: Never
        command:
          - cp -pR /tmp /minecraft/
          - java -Xms512M -Xmx1G -jar /minecraft/paper.jar --nogui 
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: hub-pv
          mountPath: /minecraft
        - name: server-properties
          mountPath: /minecraft/server.properties
          subPath: server.properties
        - name: hub-spigot
          mountPath: /minecraft/spigot.yml
          subPath: spigot.yml
      volumes:
      - name: hub-pv
        persistentVolumeClaim:
          claimName: hub-pvc
      - name: server-properties
        configMap:
          name: hub-server-properties
      - name: hub-spigot
        configMap:
          name: hub-spigot
