apiVersion: v1
kind: Service
metadata:
  name: waterfall-server-service
spec:
  type: LoadBalancer
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  selector:
    app: waterfall-server
